name=IOXESP32Audio
version=1.0.0
author=ArtronShop CO.,LTD. | schreibfaul1
maintainer=Sonthaya Nongnuch
sentence=With this library You can easily build a WebRadio with a ESP32 board with IOXESP32 Audio shield.
paragraph=Plays google tts, mp3 webradio, playlists can be m3u, pls or asx. Data format can be only mp3. It can also play MP3 files from a SD Card.
category=Device Control
url=https://github.com/ArtronShop/IOXESP32Audio
architectures=esp32
